theme: jekyll-theme-cayman
title: Szymon Jaco≈Ñ, ML Engineer
description: Witamy w koloni
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title
    sort_by: date
    sort_order: reverse
    defaults:
      - scope:
          path: ""
          type: posts
        values:
          layout: post
